[CHORE (Activate)]: run activation pipeline for dev - 2026-05-28 13:27:51

diff --git a/.github/workflows/setup_argocd.yml b/.github/workflows/setup_argocd.yml
--- a/.github/workflows/setup_argocd.yml
+++ b/.github/workflows/setup_argocd.yml
@@ -1,7 +1,18 @@
-name: Argocd Setup
+name: Argocd And Gitops Bootstrap
 
 on:
   workflow_dispatch:
+    inputs:
+      env:
+        description: Environment
+        required: true
+        default: dev
+        type: choice
+        options: [dev, prod]
+
+permissions:
+  id-token: write
+  contents: read
 
 jobs:
   bootstrap:
@@ -9,36 +20,36 @@ jobs:
     environment: development
 
     steps:
-      # --------------------------------
-      # 1. Checkout repo
-      # --------------------------------
       - name: Checkout repo
         uses: actions/checkout@v4
 
-      # --------------------------------
-      # 2. AWS credentials
-      # --------------------------------
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
           aws-region: ${{ secrets.AWS_REGION }}
 
-      - name: Configure AWS credentials
+      #- name: Check AWS credentials
+      #  run: aws sts get-caller-identity
+
+      - name: Install SOPS
         run: |
-          set -e
-          STATUS=$(kubectl get configmap cluster-readiness -n kube-system -o jsonpath='{.data.status}' 2>/dev/null || echo "notready")
+          curl -L -o sops https://github.com/getsops/sops/releases/download/v3.9.0/sops-v3.9.0.linux.amd64
+          chmod +x sops
+          sudo mv sops /usr/local/bin/sops
 
-          if [ "$STATUS" != "ready" ]; then
-            echo "❌ Cluster not ready"
+      - name: Setup AGE key
+        run: |
+          mkdir -p ~/.config/sops/age
+          echo "${{ secrets.AGE_PRIVATE_KEY }}" > ~/.config/sops/age/keys.txt
+          chmod 600 ~/.config/sops/age/keys.txt
+          test -s ~/.config/sops/age/keys.txt || {
+            echo "❌ AGE key missing"
             exit 1
-          fi
-
-          echo "Cluster ready → proceeding with GitOps"
+          }
 
       # --------------------------------
-      # 3. Setup kubeconfig (EKS access)
+      #  Setup kubeconfig (EKS access)
       # --------------------------------
       - name: Setup kubeconfig
         run: |
@@ -62,27 +73,101 @@ jobs:
           echo "=== auth test ==="
           kubectl auth can-i get pods -A || true
 
-      # --------------------------------
-      # 4. Apply ArgoCD GitHub App repo secret
-      # --------------------------------
+      - name: Check Readiness
+        run: bash scripts/check_cluster.sh
+
       - name: Apply ArgoCD GitHub App secret
         run: |
           set -e
 
-          if [ -f gitops/argocd/github-repo-secret.yaml ]; then
-            kubectl apply --validate=false -f gitops/argocd/github-repo-secret.yaml
-            echo "ArgoCD secret applied from file"
-          else
-            echo "Generating secret"
-            python3 scripts/argo_secret.py
-            kubectl apply --validate=false -f gitops/argocd/github-repo-secret.yaml
-          fi
+          SECRET_FILES=$(find gitops/secrets -type f -name "*.yaml" -print)
+          while IFS= read -r one; do
+              DECRYPTED="decrypted-$(basename "$one")"
+              echo "Decrypting secret file: $one"
+              sops -d "$one" > "$DECRYPTED"
+              kubectl apply --validate=false -f "$DECRYPTED"
+              echo "✅ $one ArgoCD secret applied from Sops"
+          done <<< "$SECRET_FILES"
+        env:
+           PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY_GITHUB }}
+           APP_ID: ${{ secrets.APP_ID_GITHUB }}
+           REPO_URL: ${{ secrets.REPO_URL }}
+           BASE_FILE: "$BASE_FILE"
 
-      # --------------------------------
-      # 5. Verify ArgoCD resources
-      # --------------------------------
       - name: Verify ArgoCD namespace access
         run: kubectl get ns argocd
 
       - name: Verify secret exists
         run: kubectl get secret -n argocd | grep github || true
+
+      - name: Generate GitHub App token
+        id: app-token
+        uses: tibdex/github-app-token@v2
+        with:
+          app_id: ${{ secrets.APP_ID_GITHUB }}
+          private_key: ${{ secrets.APP_PRIVATE_KEY_GITHUB }}
+
+      - name: Checkout repo
+        uses: actions/checkout@v4
+        with:
+          token: ${{ steps.app-token.outputs.token }}
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+
+      - name: Ensure helm is isntalled
+        run: |
+          if ! command -v helm >/dev/null 2>&1; then
+            sudo snap install helm --classic
+          fi
+
+      - name: Install Metrics Server for HPA
+        run: |
+          helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
+          helm upgrade --install metrics-server metrics-server/metrics-server \
+            -n kube-system \
+            --create-namespace
+
+      - name: Make script executable
+        run: chmod +x scripts/bootstrap_gitops.sh
+
+      - name: Run GitOps bootstrap
+        run: bash scripts/bootstrap_gitops.sh
+
+      - name: Get Metadata from Terraform
+        working-directory: iac/infra
+        env:
+          ENV: "${{ github.event.inputs.env }}"
+        run: |
+          set -euo pipefail
+          terraform init -reconfigure -backend-config="envs/${ENV}/backend.hcl"
+          CERT_ARN=$(terraform output -raw main_cert_arn 2>/dev/null || true)
+
+          if [[ -z "$CERT_ARN" ]]; then
+            echo "❌ CERT ARN is empty"
+            exit 1
+          fi
+
+          echo "CERT_ARN Found: $CERT_ARN"
+          echo "CERT_ARN=$CERT_ARN" >> $GITHUB_ENV
+
+      - name: Ensure Route53 is synced
+        env:
+          ENV: "${{ github.event.inputs.env }}"
+          DOMAIN: "${{ secrets.DOMAIN }}"
+          CERT_ARN: "${{ env.CERT_ARN }}"
+          AWS_REGION: "${{ env.AWS_REGION }}"
+        run: |
+          set -euo pipefail
+          for i in {1..8}; do
+            echo "Setting up route53 for Domain if new..."
+            if bash scripts/sync_route53.sh; then
+              echo "✅ Success on attempt $i"
+              break
+            else
+              echo "ALB not ready yet, retrying..."
+              sleep 5
+            fi
+            echo "❌ Route53 sync failed after $i attempts"
+          done
+          echo "End of Workflow!"
diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -1,26 +1,30 @@
-name: Update GitOps
+name: Runtime Image Update
 
 on:
-  workflow_run:
-    workflows: ["Build and Push Docker Images"]
-    types:
-      - completed
+  workflow_dispatch:
 
 concurrency:
-  group: gitops-update
+  group: using-commit
   cancel-in-progress: false
 
 jobs:
   update:
     runs-on: ubuntu-latest
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
 
     steps:
-      - name: Checkout GitOps repo
+      - name: Generate GitHub App token
+        id: app-token
+        uses: tibdex/github-app-token@v2
+        with:
+          app_id: ${{ secrets.APP_ID_GITHUB }}
+          private_key: ${{ secrets.APP_PRIVATE_KEY_GITHUB }}
+
+      - name: Checkout repo
         uses: actions/checkout@v4
         with:
-          repository: timzapone/kubapp-project
-          token: ${{ secrets.GITOPS_TOKEN }}
+          repository: paragon40/kubapp
+          token: ${{ steps.app-token.outputs.token }}
+          fetch-depth: 0
 
       - name: Install dependencies
         run: |
@@ -30,53 +34,31 @@ jobs:
           https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
           sudo chmod +x /usr/local/bin/yq
 
-      - name: Download artifacts
-        uses: actions/download-artifact@v4
-        with:
-          run-id: ${{ github.event.workflow_run.id }}
-          path: artifacts
-
-      # =========================
-      # VALIDATION (STRICT)
-      # =========================
-      - name: Validate artifacts
+      - name: Retrieve Currect ENV
         run: |
-          set -e
-
-          echo "Checking artifacts directory..."
-
-          if [ ! -d "artifacts" ]; then
-            echo "Artifacts directory missing"
+          set -euo pipefail
+          STATE_FILE="gitops/state/current.json"
+          if [[ ! -f "$STATE_FILE" || ! -s "$STATE_FILE" ]]; then
+            echo "❌ State File: $STATE_FILE is Missing or Empty."
             exit 1
           fi
 
-          FILES=$(find artifacts -name "*.json")
-
-          if [ -z "$FILES" ]; then
-            echo "No artifacts found"
+          STATE_ENV=$(jq -r '.env' "$STATE_FILE")
+          if [[ -z "$STATE_ENV" || "$STATE_ENV" == "null" ]]; then
+            echo "❌ ENV Source from state file Empty"
             exit 1
           fi
+          echo "Detected ENV: $STATE_ENV"
+          echo "ENV=$STATE_ENV" >> $GITHUB_ENV
 
-          echo "Validating JSON files..."
-
-          for file in $FILES; do
-            echo "Checking $file"
-            jq empty "$file" || exit 1
-          done
-
-      - name: Validate GitOps structure
-        run: ./scripts/validate_gitops.sh artifacts
-
-      # =========================
-      # APPLY GITOPS UPDATES
-      # =========================
       - name: Apply GitOps updates
         run: |
           set -e
-
-          for file in $(find artifacts -name "*.json"); do
+          ENV1="${{ env.ENV }}"
+          for file in $(find gitops/registry/$ENV1/*.json -name "*.json"); do
             SERVICE=$(jq -r .service "$file")
             IMAGE=$(jq -r .image "$file")
+            TAG=$(jq -r .tag "$file")
             ENV=$(jq -r .env "$file")
 
             if [ -z "$ENV" ] || [ "$ENV" = "null" ]; then
@@ -85,26 +67,26 @@ jobs:
             fi
 
             FILE="gitops/envs/$ENV/$SERVICE/values.yaml"
-
-            echo "Updating $SERVICE ($ENV)"
-
-            if [ ! -f "$FILE" ]; then
-              echo "Missing GitOps file: $FILE"
+            if [[ ! -f "$FILE" ]]; then
+              echo "Values File for ${SERVICE}-${ENV} NOT Found"
               exit 1
             fi
 
-            yq e ".image.repository = strenv(IMAGE)" -i "$FILE"
+            echo "Updating ${SERVICE}-${ENV}"
+            echo "Target file: $FILE"
+            echo "Image: $IMAGE"
+            echo "Tag: $TAG"
+            yq e ".image.repository = \"$IMAGE\"" -i "$FILE"
+            yq e ".image.tag = \"$TAG\"" -i "$FILE"
+            echo "Cat $FILE"
+            cat "$FILE"
           done
 
-      # =========================
-      # COMMIT CHANGES
-      # =========================
+      - name: Validate GitOps structure
+        run: ./scripts/validate_gitops.sh
+
       - name: Commit changes
         run: |
-          git config user.name "github-actions"
-          git config user.email "github-actions@github.com"
-
-          git add .
-          git diff --exit-code
-          git commit -m "gitops update from build pipeline" || exit 0
-          git push
+          ENV="${{ env.ENV }}"
+          DIR="gitops/envs/$ENV"
+          bash scripts/commit.sh  "$DIR" "Runtime IMAGE Update"
